name: Sync Liska Linux DB

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up ode.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Sync Script
        run: node sync.js
      - name: Commit and Push Updated db.json
        run: |
          git config --global user.name "Liska Bot"
          git config --global user.email "bot-liskalinux@gmail.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: automated repository sync [bot]" && git push)
